In [1]:
import json
import random
from pathlib import Path


def make_random_split(
    dataset_dir: str,
    unseen_pct: float,
    out_path: str,
    seed: int = 42,
    exts=None,
):
    """
    dataset_dir 안의 파일들 중 unseen_pct (%)를 랜덤으로 뽑아서
    unseen / train 리스트를 out_path(json)에 저장한다.

    Args:
        dataset_dir: 모션 데이터가 들어 있는 루트 폴더
        unseen_pct: 전체에서 unseen으로 뽑을 비율 (예: 20.0)
        out_path: 결과를 저장할 json 경로
        seed: 랜덤 시드 (재현용)
        exts: 사용할 파일 확장자 리스트 (예: ['.bvh', '.npy'])
              None이면 모든 파일 사용
    """
    dataset_dir = Path(dataset_dir)
    assert dataset_dir.is_dir(), f"{dataset_dir} is not a directory"

    # 파일 모으기
    if exts is None:
        files = [p for p in dataset_dir.rglob("*") if p.is_file()]
    else:
        exts = {e.lower() for e in exts}
        files = [p for p in dataset_dir.rglob("*") if p.suffix.lower() in exts]

    files = sorted(files)
    n_total = len(files)
    if n_total == 0:
        raise ValueError(f"No files found in {dataset_dir}")

    # 랜덤 셔플 후 n%를 unseen으로
    random.seed(seed)
    random.shuffle(files)

    n_unseen = int(n_total * (unseen_pct / 100.0))
    unseen_files = files[:n_unseen]
    train_files = files[n_unseen:]

    result = {
        "dataset_dir": str(dataset_dir),
        "total_files": n_total,
        "unseen_ratio": unseen_pct,
        "n_seen": len(train_files),
        "n_unseen": len(unseen_files),
        "seed": seed,
        "seen_motion": [str(p) for p in train_files],
        "unseen_motion": [str(p) for p in unseen_files],
        "seen_char": ["Abe", "Adam", "Alien Soldier", "Crypto", "Demon T Wiezzorek", "Exo Gray", "James", "Leonard"],
        "unseen_char": ["Steve"],
        "target_char": "Claire",
    }

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    print(f"Saved split to {out_path}")
    print(f"  total  : {n_total}")
    print(f"  seen  : {len(train_files)}")
    print(f"  unseen : {len(unseen_files)}")
    

if __name__ == "__main__":
    # 예시 사용법
    # python split_motion.py
    make_random_split(
        dataset_dir="./datasets/mixamo/char/Abe",
        unseen_pct=20.0,  # 전체의 20%를 unseen으로
        out_path="./config/motion_split_20%.json",
        seed=42,
        exts=[".bvh"],  # 필요 없으면 None
    )


Saved split to config\motion_split_20%.json
  total  : 565
  seen  : 452
  unseen : 113


In [2]:
data_config_path = "./config/motion_split_20%.json"
split_path = Path(data_config_path)
assert split_path.is_file(), f"{split_path} not found"

with split_path.open("r", encoding="utf-8") as f:
    data_config = json.load(f)

In [4]:
data_config['seen_char']
data_config['unseen_char']
data_config['seen_motion']
data_config['unseen_motion']
data_config['target_char']

'Claire'

In [19]:
import os

In [27]:
base = "c:\\Users\\Taeyong_Sim\\Desktop\\Motion Retargeting\\R2ET\\results\\Claire"
folders = os.listdir(base)
for folder in folders:
    path = os.path.join(base, folder)
    files = os.listdir(path)
    for file in files:
        fn = file.split('.')[0]
        ft = file.split('.')[-1].replace('bvh', '')
        os.rename(os.path.join(path, file), os.path.join(path, fn+ft+'.bvh'))

FileExistsError: [WinError 183] 파일이 이미 있으므로 만들 수 없습니다: 'c:\\Users\\Taeyong_Sim\\Desktop\\Motion Retargeting\\R2ET\\results\\Claire\\Abe\\standing idle looking ver. 2.bvh_dr2et' -> 'c:\\Users\\Taeyong_Sim\\Desktop\\Motion Retargeting\\R2ET\\results\\Claire\\Abe\\standing idle looking ver_dr2et.bvh'

In [26]:
files

['armada to esquiva.bvh_gt',
 'armada to esquiva.bvh_inp',
 'armada to esquiva.bvh_r2et',
 'armada.bvh_gt',
 'armada.bvh_inp',
 'armada.bvh_r2et',
 'au to role.bvh_gt',
 'au to role.bvh_inp',
 'au to role.bvh_r2et',
 'au.bvh_gt',
 'au.bvh_inp',
 'au.bvh_r2et',
 'back flip to uppercut.bvh_gt',
 'back flip to uppercut.bvh_inp',
 'back flip to uppercut.bvh_r2et',
 'backward walking turn.bvh_gt',
 'backward walking turn.bvh_inp',
 'backward walking turn.bvh_r2et',
 'bencao.bvh_gt',
 'bencao.bvh_inp',
 'bencao.bvh_r2et',
 'box idle.bvh_gt',
 'box idle.bvh_inp',
 'box idle.bvh_r2et',
 'box turn (2).bvh_gt',
 'box turn (2).bvh_inp',
 'box turn (2).bvh_r2et',
 'box turn.bvh_gt',
 'box turn.bvh_inp',
 'box turn.bvh_r2et',
 'box walk arc.bvh_gt',
 'box walk arc.bvh_inp',
 'box walk arc.bvh_r2et',
 'breakdance 1990 (2).bvh_gt',
 'breakdance 1990 (2).bvh_inp',
 'breakdance 1990 (2).bvh_r2et',
 'breakdance 1990 (3).bvh_gt',
 'breakdance 1990 (3).bvh_inp',
 'breakdance 1990 (3).bvh_r2et',
 'breakdan

In [33]:
%cd "c:\\Users\\Taeyong_Sim\\Desktop\\Motion Retargeting\\R2ET\\outside-code\\sdf\\sdf"

c:\Users\Taeyong_Sim\Desktop\Motion Retargeting\R2ET\outside-code\sdf\sdf


In [34]:
import numpy as np
import torch
import torch.nn.functional as F

from sdf import SDF2  # sdf.py 안에 있는 SDF2 (signed SDF 라고 가정)


def build_body_sdf_per_frame(body_vertices, faces, grid_size=32, scale_factor=0.0, device="cuda"):
    """
    body_vertices: (T, Nb, 3)  - 각 프레임의 body vertex 월드 좌표
    faces        : (F, 3)      - body mesh faces 인덱스 (Abe.npz의 rest_faces 사용 가능)
    반환:
      phi        : (T, G, G, G)         - 각 프레임별 SDF grid
      centers    : (T, 1, 3)            - 각 프레임 bounding box 중심
      scales     : (T, 1, 1)            - 각 프레임 uniform scale (스칼라)
    """
    device = torch.device(device)
    sdf2 = SDF2().to(device)

    T, Nb, _ = body_vertices.shape
    faces_torch = torch.from_numpy(faces.astype(np.int32)).to(device)

    # (T, Nb, 3)
    body_torch = torch.from_numpy(body_vertices.astype(np.float32)).to(device)

    # bounding box 계산 (SDFLoss 패턴 그대로)
    # boxes: (T, 2, 3)  -> [min, max]
    boxes = torch.zeros(T, 2, 3, device=device)
    boxes[:, 0, :] = body_torch.min(dim=1)[0]
    boxes[:, 1, :] = body_torch.max(dim=1)[0]

    # center: (T, 1, 3)
    centers = boxes.mean(dim=1, keepdim=True)

    # uniform scale (최대 축 길이 / 2, 거기에 (1+scale_factor) margin)
    # boxes[:, 1] - boxes[:, 0]: (T, 3)
    half_lengths = 0.5 * (boxes[:, 1] - boxes[:, 0])  # (T, 3)
    max_half = half_lengths.max(dim=-1)[0]            # (T,)
    scales = (1.0 + scale_factor) * max_half[:, None, None]  # (T, 1, 1)

    # [-1, 1]^3 로 정규화
    body_centered = body_torch - centers          # (T, Nb, 3)
    body_scaled = body_centered / scales          # (T, Nb, 3)

    # SDF2 는 (B, V, 3) 입력을 받는다고 가정
    with torch.no_grad():
        phi = sdf2(faces_torch, body_scaled, grid_size=grid_size)  # (T, G, G, G)

    return phi, centers, scales


def sample_sdf(phi, centers, scales, query_vertices, device="cuda"):
    """
    phi           : (T, G, G, G) - 각 프레임 SDF grid
    centers       : (T, 1, 3)
    scales        : (T, 1, 1)
    query_vertices: (T, Nq, 3)   - 각 프레임에서 SDF를 샘플링할 vertex 월드 좌표
    반환:
      sdf_vals    : (T, Nq)     - 각 query vertex의 SDF 값
    """
    device = torch.device(device)
    T, Nq, _ = query_vertices.shape
    G = phi.shape[-1]

    phi_torch = phi.to(device)  # (T, G, G, G)
    centers = centers.to(device)
    scales = scales.to(device)

    q_torch = torch.from_numpy(query_vertices.astype(np.float32)).to(device)  # (T, Nq, 3)

    # 월드 → [-1,1]^3 로 정규화
    q_centered = q_torch - centers              # (T, Nq, 3)
    q_scaled = q_centered / scales              # (T, Nq, 3)

    # grid_sample 포맷: (N, D, H, W, 3) 이지만 여기선 3D 볼륨이라
    #  -> 입력: (N, C=1, D=G, H=G, W=G), grid: (N, Nq, 1, 1, 3)
    # 여기서 N = T (프레임 수), C=1
    phi_input = phi_torch[:, None, ...]           # (T, 1, G, G, G)
    grid = q_scaled.view(T, Nq, 1, 1, 3)         # (T, Nq, 1, 1, 3)

    # align_corners=True/False 는 csrc.sdf 구현에 맞게 조정 (여기선 False 예시)
    with torch.no_grad():
        sampled = F.grid_sample(phi_input, grid, align_corners=False)  # (T, 1, Nq, 1, 1)

    sampled = sampled.view(T, Nq)
    return sampled  # torch.Tensor, (T, Nq)


def evaluate_single_sample(
    rest_faces,
    vertex_part,
    pred_vertices,      # (T, V, 3) - 평가 대상 mesh
    gt_vertices=None,   # (T, V, 3) - GT mesh (self-contact용; 없으면 관통만 평가)
    body_part_ids=(0, 1, 2),        # 예: 몸통/골반/머리 등
    limb_part_ids=(3, 4, 5, 6, 7),  # 예: 팔/다리 등
    hand_part_ids=(8, 9),           # 예: 손
    grid_size=32,
    contact_threshold=0.02,         # self-contact 판정 거리 (m 단위 or 키 정규화 후)
    device="cuda"
):
    """
    반환:
      metrics = {
        'penetration_ratio_mean': float,
        'penetration_ratio_max' : float,
        'self_contact_mean_pred_on_gt_contact': float or None,
        'num_gt_contact_frames': int
      }
    """

    # =========================
    # 0. 파트별 vertex 인덱스 분리
    # =========================
    vertex_part = np.array(vertex_part, dtype=np.int64)  # (V,)
    V = vertex_part.shape[0]
    T = pred_vertices.shape[0]

    body_mask = np.isin(vertex_part, np.array(body_part_ids, dtype=np.int64))
    limb_mask = np.isin(vertex_part, np.array(limb_part_ids, dtype=np.int64))
    hand_mask = np.isin(vertex_part, np.array(hand_part_ids, dtype=np.int64))

    body_idx = np.where(body_mask)[0]
    limb_idx = np.where(limb_mask)[0]
    hand_idx = np.where(hand_mask)[0]

    assert len(body_idx) > 0, "body_part_ids 에 해당하는 vertex가 없습니다."
    assert len(limb_idx) > 0, "limb_part_ids 에 해당하는 vertex가 없습니다."
    if gt_vertices is not None:
        assert len(hand_idx) > 0, "hand_part_ids 에 해당하는 vertex가 없습니다."

    # =========================
    # 1. 관통 지표: pred mesh 기준
    # =========================
    # 1-1) pred 기준 body vertex만 추출 → (T, Nb, 3)
    pred_body = pred_vertices[:, body_idx, :]  # (T, Nb, 3)
    faces = rest_faces  # (F, 3) – Abe.npz의 rest_faces 사용

    # 1-2) 각 프레임 body mesh로 SDF 생성 (signed SDF라고 가정)
    phi_pred, centers_pred, scales_pred = build_body_sdf_per_frame(
        pred_body, faces, grid_size=grid_size, scale_factor=0.0, device=device
    )  # phi_pred: (T, G, G, G)

    # 1-3) pred limb vertices에 대해 SDF 샘플
    pred_limb = pred_vertices[:, limb_idx, :]  # (T, Nl, 3)
    sdf_limb = sample_sdf(phi_pred, centers_pred, scales_pred, pred_limb, device=device)  # (T, Nl)

    # 관통 여부: SDF < 0 이면 body 내부 (signed SDF라고 가정)
    # unsigned SDF라면 이 부분은 다른 inside-test로 대체해야 함
    inside_mask = (sdf_limb < 0.0).float()  # (T, Nl)
    # 프레임별 관통 비율
    penetration_ratio_per_frame = inside_mask.mean(dim=1).cpu().numpy()  # (T,)

    penetration_ratio_mean = float(penetration_ratio_per_frame.mean())
    penetration_ratio_max = float(penetration_ratio_per_frame.max())

    # =========================
    # 2. self-contact: GT contact 프레임에서만
    # =========================
    self_contact_mean_pred = None
    num_gt_contact_frames = 0

    if gt_vertices is not None:
        # 2-1) GT 기준 body vertex, hand vertex
        gt_body = gt_vertices[:, body_idx, :]   # (T, Nb, 3)
        gt_hand = gt_vertices[:, hand_idx, :]   # (T, Nh, 3)

        # GT body로 SDF 생성
        phi_gt, centers_gt, scales_gt = build_body_sdf_per_frame(
            gt_body, faces, grid_size=grid_size, scale_factor=0.0, device=device
        )

        # GT hand에 대한 SDF (거리) 샘플
        sdf_gt_hand = sample_sdf(phi_gt, centers_gt, scales_gt, gt_hand, device=device)  # (T, Nh)
        dist_gt_hand = sdf_gt_hand.abs()  # signed여도 절대값이 거리

        # GT contact 프레임 마스크: 평균 거리가 threshold 이하인 프레임
        mean_gt_hand_dist = dist_gt_hand.mean(dim=1)  # (T,)
        gt_contact_mask = (mean_gt_hand_dist < contact_threshold)  # (T,)

        num_gt_contact_frames = int(gt_contact_mask.sum().item())
        if num_gt_contact_frames > 0:
            # 2-2) 동일 프레임에서 pred mesh 의 hand vertices → GT body SDF 로 거리 측정
            pred_hand = pred_vertices[:, hand_idx, :]  # (T, Nh, 3)
            sdf_pred_hand_on_gt = sample_sdf(phi_gt, centers_gt, scales_gt, pred_hand, device=device)  # (T, Nh)
            dist_pred_hand_on_gt = sdf_pred_hand_on_gt.abs()  # (T, Nh)

            # GT contact 프레임만 골라서 평균
            dist_pred_contact_frames = dist_pred_hand_on_gt[gt_contact_mask]  # (Tc, Nh)
            self_contact_mean_pred = float(dist_pred_contact_frames.mean().item())
        else:
            self_contact_mean_pred = None

    metrics = {
        "penetration_ratio_mean": penetration_ratio_mean,
        "penetration_ratio_max": penetration_ratio_max,
        "self_contact_mean_pred_on_gt_contact": self_contact_mean_pred,
        "num_gt_contact_frames": num_gt_contact_frames,
    }
    return metrics


In [ ]:
import numpy as np


shape_path = "C:/Users/Taeyong_Sim/Desktop/Motion Retargeting/R2ET/datasets/mixamo/shape/Adam.npz"

# 1) Abe.npz 로드
abe = np.load(shape_path)
rest_faces   = abe["rest_faces"]      # (F, 3)
vertex_part  = abe["vertex_part"]     # (V,)

# 2) 어떤 방식이든 BVH + 스키닝을 통해 (T, V, 3) 형태의
#    pred_vertices, gt_vertices 를 준비했다고 가정
#    (이 부분은 네가 이미 Blender/파이프라인에서 구현해둔 걸 그대로 쓰면 됨)
pred_vertices = ...  # np.ndarray, shape (T, V, 3)
gt_vertices   = ...  # np.ndarray, shape (T, V, 3)

# 3) vertex_part 라벨에 따라 body/limb/hand id 지정
#    (여기 숫자는 예시니까, 실제 Abe.npz에 맞게 조정 필요)
body_ids = (0, 1, 2, 3, 4, 5)         # 예: torso/hip/head
limb_ids = (6, 7, 10, 11, 14, 15, 16, 18, 19, 20)   # 예: upper/lower arm, upper/lower leg 등
hand_ids = (17, 21)            # 예: left/right hand

metrics = evaluate_single_sample(
    rest_faces,
    vertex_part,
    pred_vertices,
    gt_vertices=gt_vertices,
    body_part_ids=body_ids,
    limb_part_ids=limb_ids,
    hand_part_ids=hand_ids,
    grid_size=32,
    contact_threshold=0.02,  # 예: 캐릭터 키 정규화 후 2cm 정도
    device="cuda"
)

print("penetration_ratio_mean:", metrics["penetration_ratio_mean"])
print("penetration_ratio_max :", metrics["penetration_ratio_max"])
print("num_gt_contact_frames  :", metrics["num_gt_contact_frames"])
print("self_contact_mean_pred_on_gt_contact:",
      metrics["self_contact_mean_pred_on_gt_contact"])


In [7]:
import numpy as np

In [8]:
quat = np.load('C:/Users/Taeyong_Sim/Desktop/Motion Retargeting/R2ET/datasets/mixamo/q/Adam/breakdance footwork to idle (2)_quat.npy')
seq = np.load('C:/Users/Taeyong_Sim/Desktop/Motion Retargeting/R2ET/datasets/mixamo/q/Adam/breakdance footwork to idle (2)_seq.npy')
skel = np.load('C:/Users/Taeyong_Sim/Desktop/Motion Retargeting/R2ET/datasets/mixamo/q/Adam/breakdance footwork to idle (2)_skel.npy')
shape = np.load('C:/Users/Taeyong_Sim/Desktop/Motion Retargeting/R2ET/datasets/mixamo/shape/Adam.npz')
local_mean = np.load('C:/Users/Taeyong_Sim/Desktop/Motion Retargeting/R2ET/datasets/r2et/stats/mixamo_local_motion_mean.npy')

In [15]:
shape['rest_body_vertices']

array([[ 3.41560864, 54.66285706,  4.68634124],
       [ 4.35260868, 54.72817993,  3.89484115],
       [ 1.32550824, 54.0843811 ,  6.30764098],
       ...,
       [-6.09315252,  1.8399353 , 13.2541246 ],
       [-7.53518486,  1.96778107, 12.70286746],
       [-0.12148996,  2.25029755,  3.20064969]])

In [13]:
list(shape.keys())

['skinning_weights',
 'joint_names',
 'root_orient',
 'rest_vertices',
 'rest_faces',
 'skeleton',
 'subject',
 'vertex_part',
 'rest_body_vertices',
 'rest_arm_vertices',
 'body_width',
 'full_width',
 'joint_shape']

In [9]:
list(shape.keys())

['skinning_weights',
 'joint_names',
 'root_orient',
 'rest_vertices',
 'rest_faces',
 'skeleton',
 'subject',
 'vertex_part',
 'rest_body_vertices',
 'rest_arm_vertices',
 'body_width',
 'full_width',
 'joint_shape']

In [187]:
states = seq[:,:-4]

joints = states[:, :-4]
root_x = states[:, -4]
root_y = states[:, -3]
root_z = states[:, -2]
root_r = states[:, -1]

joints = joints.reshape(joints.shape[:1] + (-1, 3))

In [249]:
joints[:, 9,1]

array([16.93368373, 17.36649631, 18.04267818, 19.16547303, 20.60522346,
       22.46866982, 24.79324906, 27.49899373, 30.36548165, 33.05354992,
       35.18042468, 36.43144999, 36.67381508, 35.9817343 , 34.57562938,
       32.7142502 , 30.60739533, 28.38822573, 26.13565456, 23.91094691,
       21.78089826, 19.83707553, 18.23520958, 17.21038019, 16.98704699,
       17.60457399, 18.7584254 , 19.71835069, 19.44830495, 17.64944112,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504])

In [250]:
root_y

array([-0.289093, -0.309258, -0.281296, -0.210411, -0.170631, -0.138352,
       -0.0849  ,  0.092316,  0.164704,  0.215019,  0.207718,  0.177009,
        0.094033,  0.0783  ,  0.118095,  0.141091,  0.171379,  0.142898,
        0.034066,  0.020096,  0.025245,  0.034836,  0.036171,  0.04171 ,
        0.038193,  0.006172, -0.08548 , -0.076637, -0.066284, -0.126717,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ])

In [251]:
import numpy as np

def get_height(joints):
    """
    joints: (J, 3) 또는 (J, T, 3)
    return: height (스칼라 또는 프레임별 height)
    """
    # 머리→루트
    segs = [
        (5, 4),
        (4, 3),
        (3, 2),
        (2, 1),
        (1, 0),
        # 루트→다리
        (0, 6),
        (6, 7),
        (7, 8),
        (8, 9),
    ]
    
    lengths = []
    for i, j in segs:
        diff = joints[i] - joints[j]  # (..., 3)
        l = np.sqrt((diff ** 2).sum(axis=-1))  # (...)  마지막 축(xyz)만 norm
        lengths.append(l)
    
    # lengths를 모두 더함
    height = np.sum(np.stack(lengths, axis=0), axis=0)  # 프레임별 또는 스칼라
    return height


In [252]:
get_height(joints[0])

169.52954271175298

In [253]:
joints.shape

(60, 22, 3)

In [254]:
root_y[:-1] - root_y[1:]

array([ 0.020165, -0.027962, -0.070885, -0.03978 , -0.032279, -0.053452,
       -0.177216, -0.072388, -0.050315,  0.007301,  0.030709,  0.082976,
        0.015733, -0.039795, -0.022996, -0.030288,  0.028481,  0.108832,
        0.01397 , -0.005149, -0.009591, -0.001335, -0.005539,  0.003517,
        0.032021,  0.091652, -0.008843, -0.010353,  0.060433, -0.126717,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ])

In [255]:
joints[:,9, 1]

array([16.93368373, 17.36649631, 18.04267818, 19.16547303, 20.60522346,
       22.46866982, 24.79324906, 27.49899373, 30.36548165, 33.05354992,
       35.18042468, 36.43144999, 36.67381508, 35.9817343 , 34.57562938,
       32.7142502 , 30.60739533, 28.38822573, 26.13565456, 23.91094691,
       21.78089826, 19.83707553, 18.23520958, 17.21038019, 16.98704699,
       17.60457399, 18.7584254 , 19.71835069, 19.44830495, 17.64944112,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504])

In [256]:
root_y[9]

0.2150189999999981

In [257]:
joints[:,9,1] + root_y

array([16.64459073, 17.05723831, 17.76138218, 18.95506203, 20.43459246,
       22.33031782, 24.70834906, 27.59130973, 30.53018565, 33.26856892,
       35.38814268, 36.60845899, 36.76784808, 36.0600343 , 34.69372438,
       32.8553412 , 30.77877433, 28.53112373, 26.16972056, 23.93104291,
       21.80614326, 19.87191153, 18.27138058, 17.25209019, 17.02523999,
       17.61074599, 18.6729454 , 19.64171369, 19.38202095, 17.52272412,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504,
       16.93364504, 16.93364504, 16.93364504, 16.93364504, 16.93364504])

In [258]:
%cd c:\Users\Taeyong_Sim\Desktop\Motion Retargeting\R2ET\outside-code

c:\Users\Taeyong_Sim\Desktop\Motion Retargeting\R2ET\outside-code


In [259]:
from Quaternions import Quaternions

In [281]:
root_y.shape

torch.Size([1, 577])

In [260]:
states = seq[:,:-4].copy()
joints = states[:, :-4]
root_y = states[:, -3]

joints = joints.reshape(joints.shape[:1] + (-1, 3))

In [261]:
joints[:,9,1] + root_y[0]

array([ 6.03350892e-01, -5.60864056e-01, -1.82099887e+00, -3.26817404e+00,
       -4.81818771e+00, -5.65847899e+00, -6.51724409e+00, -7.74841022e+00,
       -9.26197960e+00, -1.01944272e+01, -1.10111417e+01, -1.16907665e+01,
       -1.21334575e+01, -1.32523353e+01, -1.46014657e+01, -1.62419333e+01,
       -1.81881180e+01, -1.97293294e+01, -1.98380323e+01, -2.00391787e+01,
       -2.04389243e+01, -2.09100196e+01, -2.12370839e+01, -2.15362059e+01,
       -2.22525106e+01, -2.30368769e+01, -2.38888669e+01, -2.45537490e+01,
       -2.54107115e+01, -2.60676392e+01, -2.64287343e+01, -2.64444310e+01,
       -2.64753342e+01, -2.68485954e+01, -2.76903215e+01, -2.95294204e+01,
       -2.93053449e+01, -2.68881448e+01, -2.45463980e+01, -2.26553130e+01,
       -2.15735100e+01, -2.15235690e+01, -2.20407567e+01, -2.27224808e+01,
       -2.38033437e+01, -2.45546151e+01, -2.48186896e+01, -2.63385029e+01,
       -2.82967669e+01, -2.88702644e+01, -2.91198182e+01, -2.92006405e+01,
       -2.92251443e+01, -

In [262]:
def put_in_world2(states):
    joints = states[:,:, :-4]
    root_y = states[:,:, -3]

    joints = joints.reshape(joints.shape[:2] + (-1, 3))
    joints_y = joints[:,:,:,1]

    translation = np.array([[0, 0, 0]])

    for i in range(len(joints)):
        joints[i, :, 1] = joints[i, :, 1] + translation[0, 1]
        translation = translation + np.array(
            [0, root_y[i], 0]
        )

    return joints[None]

In [263]:
import torch

In [264]:
root_y = states[:, -3]

In [265]:
root_y

array([ 1.164246e+00,  1.260193e+00,  1.447166e+00,  1.564755e+00,
        1.710647e+00,  1.685971e+00,  1.815319e+00,  1.749080e+00,
        1.696102e+00,  1.619286e+00,  1.502007e+00,  1.248004e+00,
        1.298760e+00,  1.249897e+00,  1.182175e+00,  1.102657e+00,
        8.618200e-01,  5.612760e-01,  4.798470e-01,  3.504830e-01,
        2.038800e-01,  1.615140e-01,  2.782210e-01,  6.579290e-01,
        7.427060e-01,  8.854600e-01,  7.210160e-01,  8.889080e-01,
        6.634070e-01,  5.661620e-01,  4.876630e-01,  5.376430e-01,
        6.355520e-01,  5.248950e-01,  3.469840e-01, -5.606000e-02,
       -7.597400e-02, -5.387100e-02, -4.843100e-02, -7.203000e-03,
        1.322640e-01,  7.089200e-02,  2.379600e-02,  1.297800e-02,
        4.710400e-02,  1.314010e-01,  1.040340e-01,  8.277900e-02,
        9.613800e-02, -2.659600e-02, -1.635290e-01, -2.966990e-01,
       -3.336260e-01, -4.942780e-01, -5.322720e-01, -7.658770e-01,
       -8.835910e-01, -1.293129e+00, -1.360283e+00, -1.510910e

In [266]:
states = seq[:,:-4].copy()
states = torch.tensor(states)[None]

localB_rt = states[:,:, :-4].reshape(states.shape[:2]+(-1, 3))
globalB_rt = states[:,:, -4:]

In [272]:
localB_rt[:,:,9]

tensor([[[ 11.8736,  -0.5609,  32.4502],
         [ 10.7989,  -1.7251,  33.2831],
         [ 10.1790,  -2.9852,  34.6919],
         ...,
         [ 12.0784, -65.6826,   9.4504],
         [ 12.0313, -65.6408,   9.4971],
         [ 11.9908, -65.5990,   9.5392]]], dtype=torch.float64)

In [273]:
joint_lst = list(range(22))
joints_y = localB_rt[:,:,joint_lst, 1]
root_y = globalB_rt[...,-3]

translation_y = torch.zeros_like(root_y)
translation_y[:,1:] = torch.cumsum(root_y[:,:-1], dim=1)
translation_y = translation_y[...,None]

global_joints_y = joints_y + translation_y

In [280]:
(global_joints_y.numpy()[:,:,9] < -10).any()

False

In [269]:
global_joints_y.numpy()[:,:,9][0, 102]

-0.5790549724849385

In [454]:
states = seq[:,:-4].copy()
joints = states[:, :-4]
joints = joints.reshape(joints.shape[:1] + (-1, 3))
joints_y = joints[:,:,1]

In [469]:
(torch.tensor(joints_y)[1:] + torch.cumsum(root_y[:-1], dim=0)[...,None])[:,9]

tensor([5.1593, 5.0269, 4.9727, 4.8668, 4.6980, 4.5216, 4.3342, 4.5211, 4.8421,
        5.3740, 5.5823, 5.3510, 4.9834, 4.3646, 3.1640, 2.2162, 1.6074, 1.3581,
        1.1678, 0.8841, 0.6435, 0.4350, 0.3402, 0.2580, 0.1583, 0.1912, 0.2185,
        0.2305, 0.2370, 0.2439, 0.2444, 0.2438, 0.2437, 0.2437, 0.2440, 0.2445,
        0.2450, 0.2454, 0.2456, 0.2460, 0.2464, 0.2468, 0.2472, 0.2474, 0.2474,
        0.2479, 0.2480, 0.2484, 0.2482, 0.2483, 0.2482, 0.2477, 0.2472, 0.2468,
        0.2465, 0.2458, 0.2532, 0.2807, 0.3349, 0.3727, 0.4223, 0.5922, 1.0151,
        1.4820, 1.7000, 2.0273, 2.9004, 3.4471, 3.8086, 4.1026, 4.2243, 4.3277,
        4.3460, 4.2184, 4.1269, 4.0212, 3.8554, 3.8433, 3.9707, 4.0998, 4.2463,
        4.5069, 4.7844, 5.0595, 5.2045, 5.2876, 5.3826, 5.2654],
       dtype=torch.float64)

In [470]:
after

array([5.26563226, 5.15934069, 5.02690604, 4.97268973, 4.86679891,
       4.69802366, 4.52163256, 4.33422074, 4.52112352, 4.84210959,
       5.37396874, 5.58233355, 5.35096014, 4.98343326, 4.36455535,
       3.16401795, 2.21624793, 1.60744142, 1.35806646, 1.16776915,
       0.88405898, 0.6435454 , 0.43495448, 0.34020833, 0.25801018,
       0.15833575, 0.19120604, 0.21851349, 0.23050253, 0.23696748,
       0.24392333, 0.24437389, 0.24383097, 0.24371962, 0.24371134,
       0.24397652, 0.24447977, 0.24495942, 0.24539883, 0.24563659,
       0.2459746 , 0.2464105 , 0.24675764, 0.24716896, 0.24743511,
       0.24741282, 0.24794456, 0.24795092, 0.24838121, 0.24817766,
       0.24829706, 0.24818749, 0.24770422, 0.24717663, 0.24684778,
       0.24648923, 0.24583485, 0.25320263, 0.28069437, 0.33490564,
       0.37273349, 0.42225195, 0.59220724, 1.01505564, 1.48204409,
       1.69996008, 2.02726404, 2.90041085, 3.44709931, 3.80855203,
       4.10256528, 4.22426874, 4.32774748, 4.34604491, 4.21837

In [450]:
root_y = torch.tensor(root_y)

In [465]:
torch.tensor(joints_y).shape

torch.Size([89, 22])

In [466]:
torch.cumsum(root_y[:-1], dim=0)[...,None].shape

torch.Size([88, 1])

In [411]:
states = seq[:,:-4].copy()
result = put_in_world2(states)

In [412]:
after = result[0,:,9,1].copy()

In [256]:
before = result[0,:,9,1].copy()

In [197]:
%cd c:\Users\Taeyong_Sim\Desktop\Motion Retargeting\R2ET\

c:\Users\Taeyong_Sim\Desktop\Motion Retargeting\R2ET


In [198]:
from os import listdir
from os.path import join

In [243]:
i = 0
diff_motion = {}

data_path = './datasets/mixamo/q'
folders = ['Adam']
for folder_name in folders:
    files = [
        f
        for f in listdir(join(data_path, folder_name))
        if not f.startswith(".") and f.endswith("_seq.npy")
    ]
    for cfile in files:
        file_name = cfile[:-8]
        # Real joint positions
        positions = np.load(
            join(data_path, folder_name, file_name + "_skel.npy")
        )

        # After processed (Maybe, last 4 elements are dummy values)
        sequence = np.load(
            join(data_path, folder_name, file_name + "_seq.npy")
        )

        # foot contact
        foot_contact = sequence[:, -4:]

        # Processed global positions (#frames, 4)
        offset = sequence[:, -8:-4]

        # Processed local positions (#frames, #joints, 3)
        sequence = np.reshape(sequence[:, :-8], [sequence.shape[0], -1, 3])
        positions[:, 0, :] = sequence[:, 0, :]  # root joint

        if any(sequence[:,9,1] < -50):
            i += 1
            print(file_name)
            print([np.where(sequence[:,9,1] < -10)])
            print(sequence[:,9,1][np.where(sequence[:,9,1] < -10)])

            diff_motion[file_name] = ([np.where(sequence[:,9,1] < -10)], sequence[:,9,1][np.where(sequence[:,9,1] < -10)])

breakdance footwork to idle (2)
[(array([  8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,
        21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
        34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,
        47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
        60,  61,  62,  63,  64,  65,  66, 213, 214, 220, 221, 222, 223,
       224, 225, 226, 227, 228, 229, 231, 232, 266, 267, 268, 274, 275,
       276, 277, 278, 279, 280, 281, 282, 283, 302, 303, 304, 305, 306,
       307, 308, 309, 335, 336, 337, 338, 339, 340, 423, 424, 425, 426,
       427, 428, 429, 430, 431, 455, 456, 457, 458, 459, 460, 461, 483,
       484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496,
       497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509,
       510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522,
       523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535,
       536, 537, 538, 539, 540

In [ ]:
diff_motion['breakdance footwork to idle (2)']

([(array([  8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,
           21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
           34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,
           47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
           60,  61,  62,  63,  64,  65,  66, 213, 214, 220, 221, 222, 223,
          224, 225, 226, 227, 228, 229, 231, 232, 266, 267, 268, 274, 275,
          276, 277, 278, 279, 280, 281, 282, 283, 302, 303, 304, 305, 306,
          307, 308, 309, 335, 336, 337, 338, 339, 340, 423, 424, 425, 426,
          427, 428, 429, 430, 431, 455, 456, 457, 458, 459, 460, 461, 483,
          484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496,
          497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509,
          510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522,
          523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535,
          536, 537, 538, 

In [285]:
globalB_rt.shape

torch.Size([1, 577, 4])

In [289]:
globalB_rt[0][:60,:-1].sum(axis=0).shape

torch.Size([3])

In [292]:
offsetB = globalB_rt[0][:60,:-1].sum(axis=0)

In [310]:
import torch

def count_parameters_in_pt_file(file_path):
    """
    Loads a .pt or .pth file containing a state_dict and sums the total number of parameters.

    Args:
        file_path (str): The path to the PyTorch model file (e.g., 'model_weights.pt').

    Returns:
        int: The total count of parameters.
    """
    try:
        # Load the state_dict from the file. It is a Python dictionary.
        # Use map_location='cpu' if the file was saved on a GPU and you are loading
        # it on a machine with only a CPU to avoid errors.
        checkpoint = torch.load(file_path, map_location='cpu')

        # Check if the loaded object is a dictionary (common for state_dict files)
        if isinstance(checkpoint, dict):
            # The 'state_dict' might be nested within a checkpoint dictionary
            # (which often includes optimizer state, epoch number, etc.).
            # If it's a general checkpoint, look for the 'model_state_dict' key.
            if 'model_state_dict' in checkpoint:
                state_dict = checkpoint['model_state_dict']
            else:
                # Assume the loaded object *is* the state_dict itself
                state_dict = checkpoint
        else:
            print("Loaded file is not a dictionary. Cannot count parameters.")
            return 0

        total_params = 0
        # Iterate over all parameter tensors in the state dictionary
        for param_name, parameter_tensor in state_dict.items():
            # Add the number of elements (numel) in the tensor to the total count
            total_params += parameter_tensor.numel()
            # Optional: print individual parameter counts
            # print(f"{param_name}: {parameter_tensor.numel()} parameters")

        return total_params

    except Exception as e:
        print(f"An error occurred: {e}")
        return 0

# --- Usage Example ---
# Replace 'your_model_file.pt' with the actual path to your file
file_path = 'c:/Users/Taeyong_Sim/Desktop/Motion Retargeting/R2ET/pretrain/shape_aware.pt'
parameter_sum = count_parameters_in_pt_file(file_path)
print(f"\nTotal number of parameters in R2ET total: {parameter_sum}")

file_path = 'c:/Users/Taeyong_Sim/Desktop/Motion Retargeting/R2ET/pretrain/skeleton_aware_pre.pt'
parameter_sum = count_parameters_in_pt_file(file_path)
print(f"\nTotal number of parameters in R2ET skel: {parameter_sum}")

file_path = 'c:/Users/Taeyong_Sim/Desktop/Motion Retargeting/R2ET/work_dir/student/hd_128/1202_1/distilled_r2et_ret-10.pt'
parameter_sum = count_parameters_in_pt_file(file_path)
print(f"\nTotal number of parameters in DistilledR2ET: {parameter_sum}")

file_path = 'c:/Users/Taeyong_Sim/Desktop/Motion Retargeting/R2ET/work_dir/student/hd_64/1202_1/distilled_r2et_ret-10.pt'
parameter_sum = count_parameters_in_pt_file(file_path)
print(f"\nTotal number of parameters in DistilledR2ET: {parameter_sum}")

file_path = 'c:/Users/Taeyong_Sim/Desktop/Motion Retargeting/R2ET/work_dir/student/hd_64/1202_2/distilled_r2et_ret-10.pt'
parameter_sum = count_parameters_in_pt_file(file_path)
print(f"\nTotal number of parameters in DistilledR2ET: {parameter_sum}")




Total number of parameters in R2ET total: 1470082

Total number of parameters in R2ET skel: 457540

Total number of parameters in DistilledR2ET: 488450

Total number of parameters in DistilledR2ET: 246850

Total number of parameters in DistilledR2ET: 6161282


In [304]:
checkpoint = torch.load(file_path, map_location='cpu')

In [308]:
checkpoint.get('model', checkpoint) == checkpoint

True

In [ ]:
0.0040 --> 0.0026: 1/6
or
0.0040 --> 0.0020: 1*4